import mongoose from "mongoose";

const patientSchema = new mongoose.Schema({
  title: { type: String },
  firstName: { type: String, required: true },
  lastName: { type: String, required: true },
  gender: { type: String },
  age: { type: Number, required: true, min: 0 },
  dob: { type: Date },
  education: { type: String },
  maritalStatus: { type: String },
  bloodGroup: { type: String },
  countryBirth: { type: String },
  nationality: { type: String },
  motherTounge: { type: String },
  occupation: { type: String },
  religion: { type: String },
  mobile: { type: String, required: true },
  alernativeMobile: { type: String },
  email: {
    type: String,
    required: true,
    match: [/.+\@.+\..+/, "Invalid email format"],
  },
  dependentType: { type: String },
  dependentName: { type: String },
  dependentRelation: { type: String },
  dependentMobile: { type: String },
  dependentEmail: {
    type: String,
    match: [/.+\@.+\..+/, "Invalid email format"],
  },
  addressLine1: { type: String, required: true },
  addressLine2: { type: String },
  state: { type: String, required: true },
  city: { type: String, required: true },
  pincode: { type: String },
  idProofType: { type: String },
  idProofNumber: { type: String },
  idProofIssuedCountry: { type: String },
  ABHANumber: { type: String },
  reasonOfVisit: { type: String },
  referredBy: { type: String },
  referredByOther: { type: String },
  referredByDoctor: { type: String },
  marketingSource: { type: String },
  intepreter: { type: Boolean },
  intepreteName: { type: String },
  isPatientSurrogate: { type: Boolean },
  isPatientDeceased: { type: Boolean },
  detailsOfDeath: { type: String },
  isPatientInsured: { type: Boolean },
  insuranceCompany: { type: String },
  insuranceSponsorName: { type: String },
  insurancePolicyNumber: { type: String },
  insurancePolicyHolderName: { type: String },
  insuranceAmountEligible: { type: String },
  image: { type: mongoose.Schema.Types.Mixed },
  remarks: { type: String },
});

const Patient = mongoose.model("Patient", patientSchema);

export default Patient;
